# Development configuration for FVS-Python

species:
  LP:
    code: "LP"
    name: "Loblolly Pine"
    min_dbh: 0.1
    max_dbh: 40.0
    min_height: 4.5
    max_height: 200.0
    min_crown_ratio: 0.2
    max_crown_ratio: 0.9
  SP:
    code: "SP"
    name: "Shortleaf Pine"
    min_dbh: 0.1
    max_dbh: 40.0
    min_height: 4.5
    max_height: 200.0
    min_crown_ratio: 0.2
    max_crown_ratio: 0.9
  LL:
    code: "LL"
    name: "Longleaf Pine"
    min_dbh: 0.1
    max_dbh: 40.0
    min_height: 4.5
    max_height: 200.0
    min_crown_ratio: 0.2
    max_crown_ratio: 0.9
  SA:
    code: "SA"
    name: "Slash Pine"
    min_dbh: 0.1
    max_dbh: 40.0
    min_height: 4.5
    max_height: 200.0
    min_crown_ratio: 0.2
    max_crown_ratio: 0.9

growth_model:
  height_diameter_model: "curtis_arney"
  small_tree_threshold: 3.0
  large_tree_threshold: 5.0
  timestep: 1  # Shorter timestep for debugging

paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  external_data_dir: "data/external"
  database_path: "data/processed/fvspy_dev.db"

logging:
  level: "DEBUG"
  file_path: "logs/development.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(pathname)s:%(lineno)d"

system:
  n_jobs: 1  # Single process for debugging
  random_seed: 42
  cache_dir: ".cache/development" 