[height_diameter.curtis_arney]
description = "Curtis-Arney height-diameter equation"
formula = "HT = 4.5 + P2 * exp(-P3 * DBH^P4)"
small_dbh_formula = "HT = ((4.5 + P2 * exp(-P3 * 3.0^P4) - 4.51) * (DBH-Dbw)/(3-Dbw)) + 4.51"
parameters = [
    { name = "P2", description = "Coefficient P2" },
    { name = "P3", description = "Coefficient P3" },
    { name = "P4", description = "Coefficient P4" },
    { name = "Dbw", description = "Diameter breakpoint for small trees" },
]
dbh_threshold = 3.0

[height_diameter.wykoff]
description = "Wykoff height-diameter equation for calibration"
formula = "HT = 4.5 + EXP(B1 + B2/(DBH+1.0))"
parameters = [
    { name = "B1", description = "Coefficient B1" },
    { name = "B2", description = "Coefficient B2" },
]

[bark_ratio]
description = "Bark ratio equations for converting between inside and outside bark diameter"
formula = "DIB = b1 + b2 * DOB"
ratio_formula = "BRATIO = DIB / DOB"
bounds = "0.80 < BRATIO < 0.99"
parameters = [
    { name = "b1", description = "Intercept coefficient" },
    { name = "b2", description = "Slope coefficient" },
]

[crown_ratio]
description = "Crown ratio estimation equations"

[crown_ratio.acr_equations."4.3.1.3"]
description = "ACR equation type 3"
formula = "ACR = exp[d0 + (d1 * ln(RELSDI)) + (d2 * RELSDI))]"
parameters = [
    "d0",
    "d1",
    "d2",
]

[crown_ratio.acr_equations."4.3.1.4"]
description = "ACR equation type 4"
formula = "ACR = exp[d0 + (d1 * ln(RELSDI))]"
parameters = [
    "d0",
    "d1",
]

[crown_ratio.acr_equations."4.3.1.5"]
description = "ACR equation type 5"
formula = "ACR = d0 + (d2 * RELSDI)"
parameters = [
    "d0",
    "d2",
]

[crown_ratio.acr_equations."4.3.1.6"]
description = "ACR equation type 6"
formula = "ACR = d0 + (d1 * log10(RELSDI))"
parameters = [
    "d0",
    "d1",
]

[crown_ratio.acr_equations."4.3.1.7"]
description = "ACR equation type 7"
formula = "ACR = RELSDI / ((d0 * RELSDI) + d1)"
parameters = [
    "d0",
    "d1",
]

[crown_ratio.weibull]
description = "Weibull distribution for individual tree crown ratio estimation"
parameters = [
    { name = "a", description = "Location parameter" },
    { name = "b0", description = "Scale intercept" },
    { name = "b1", description = "Scale slope" },
    { name = "c", description = "Shape parameter" },
]

[crown_ratio.weibull.formulas]
a = "A = a"
b = "B = b0 + b1 * ACR, bounded to be greater than 3.0"
c = "C = c, bounded to be greater than 2.0"
crown_ratio = "Y = A + B(-ln(1-X))^(1/C)"

[crown_ratio.scale_factor]
description = "Density-dependent scaling factor for crown ratio"
formula = "SCALE = 1 - 0.00167 * (CCF - 100)"
bounds = "0.3 < SCALE < 1.0"
