[transformation]
description = "Site index transformation equations for converting between species"

[transformation.equations]
relative_site_index = "RISP = (SIsite - SImin) / (SImax - SImin)"
transformation_index = "MGSPIX = A + B * (RSISP * (SIGmax - SIGmin) + SIGmin)"
group_relative_si = "MGRSI = ((C + D * MGSPIX) - SIGmin) / (SIGmax - SIGmin)"
species_site_index = "SISP = MGRSI * (SImax - SImin) + SImin"

[transformation.variables]
RSISP = "Relative site index of site species"
SIsite = "Site index of site species"
SImin = "Site index minimum of species"
SImax = "Site index maximum of species"
MGSPIX = "Site index transformation index for the site species group"
SIGmin = "Site index minimum of site species group"
SIGmax = "Site index maximum of site species group"
MGRSI = "Relative site index of each site index group"
SISP = "Species site index"

