functional_forms_file = "functional_forms.yaml"
site_index_transformation_file = "site_index_transformation.yaml"

[metadata]
variant = "SN"
variant_name = "Southern"
description = "Parameters for the Southern (SN) variant of FVS covering southeastern US"
source = "FVS Southern Variant Overview, April 2024"

[species.FR]
name = "fir"
file = "species/fr_fir.yaml"

[species.JU]
name = "juniper"
file = "species/ju_juniper.yaml"

[species.PI]
name = "spruce"
file = "species/pi_spruce.yaml"

[species.PU]
name = "sand pine"
file = "species/pu_sand_pine.yaml"

[species.SP]
name = "shortleaf pine"
file = "species/sp_shortleaf_pine.yaml"

[species.SA]
name = "slash pine"
file = "species/sa_slash_pine.yaml"

[species.SR]
name = "spruce pine"
file = "species/sr_spruce_pine.yaml"

[species.LL]
name = "longleaf pine"
file = "species/ll_longleaf_pine.yaml"

[species.TM]
name = "table mountain pine"
file = "species/tm_table_mountain_pine.yaml"

[species.PP]
name = "pitch pine"
file = "species/pp_pitch_pine.yaml"

[species.PD]
name = "pond pine"
file = "species/pd_pond_pine.yaml"

[species.WP]
name = "eastern white pine"
file = "species/wp_eastern_white_pine.yaml"

[species.LP]
name = "loblolly pine"
file = "species/lp_loblolly_pine.yaml"

[species.VP]
name = "Virginia pine"
file = "species/vp_virginia_pine.yaml"

[species.BY]
name = "baldcypress"
file = "species/by_baldcypress.yaml"

[species.PC]
name = "pondcypress"
file = "species/pc_pondcypress.yaml"

[species.HM]
name = "hemlock"
file = "species/hm_hemlock.yaml"

[species.FM]
name = "southern sugar maple"
file = "species/fm_southern_sugar_maple.yaml"

[species.BE]
name = "boxelder"
file = "species/be_boxelder.yaml"

[species.RM]
name = "red maple"
file = "species/rm_red_maple.yaml"

[species.SV]
name = "silver maple"
file = "species/sv_silver_maple.yaml"

[species.SM]
name = "sugar maple"
file = "species/sm_sugar_maple.yaml"

[species.SU]
name = "sweetgum"
file = "species/su_sweetgum.yaml"

[species.YP]
name = "tuliptree"
file = "species/yp_tuliptree.yaml"

[species.WO]
name = "white oak"
file = "species/wo_white_oak.yaml"

[species.OS]
name = "other softwood"
file = "species/os_other_softwood.yaml"

[species.OH]
name = "other hardwood"
file = "species/oh_other_hardwood.yaml"

[species.OT]
name = "other"
file = "species/ot_other.yaml"
